language: python

dist: xenial

matrix:
  include:
    - python: 3.6
      env:
        - TESTS=true
    - python: 3.7
      env:
        - TESTS=true
    - python: 3.8
      env:
        - TESTS=true

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pyflakes pytest pytest-doctestplus numpy
  - source activate test-environment

script:
  - set -e
  - pyflakes .
  - python -We:invalid -We::SyntaxWarning -m compileall -f -q ndindex/
  - pytest
  # # Make sure it installs
  # - python setup.py install
