[package]
name = "simple_slice_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "simple_slice_rust"
crate-type = ["cdylib"]
path = "simple_slice_rust.rs"

[dependencies]
pyo3 = { version = "0.21.1", features = ["extension-module"] }
