name: Docs
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          set -x
          set -e
          python -m pip install -r docs/requirements.txt
      - name: In-place build
        run: |
          python setup.py build_ext --inplace

      - name: Build Docs
        run: |
          cd docs
          make html

      # Note, the gh-pages deployment requires setting up a SSH deploy key.
      # See
      # https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          folder: docs/_build/html
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          clean-exclude: benchmarks/
