name: Free Threading Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.2"
          python-version: 3.13t
          enable-cache: false
      - name: Set up Python
        run: uv python install
      - name: Install Dependencies
        run: |
          uv pip install numpy pytest-cov pytest-timeout pytest-durations pytest-run-parallel sympy hypothesis
      - name: Disable Coverage # see gh-198
        run: |
          sed -i '/plugins = Cython.Coverage/d' .coveragerc
          sed -i 's/addopts/\#addopts/' pytest.ini
      - name: Editable build
        run: |
          uv pip install -v -e .
      - name: Run Tests
        run: |
          set -xe
          uv run --no-project python -We:invalid -We::SyntaxWarning -m compileall -f -q ndindex/
          uv run --no-project python -m pytest --parallel-threads=2 --iterations=2 -v -s \
                 --timeout=600 --durations=10 -m "not hypothesis and not thread_unsafe and not flakes"
